### ISSUE TITLE
TECHX-1.2: regional ocean 4D LETKF / 4DEnVar

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#875]
Run experiments with the same configuration that were done for the regional 3dvar, letkf, and 3DEnVAR, but with a hybrid LETKF-4DEnVAR.

* fix any bugs we find along the way
* run over the same 4 month test period and evaluate the performance

* [x] Modify workflow to save 4D forecasts
* [x] Add support for 3DFGAT
* [x] Add support for 4DEnVAR 
* [ ] run initial experiments

**Comment by travissluka** [comment]
There is still work to be done on the 4denvar

**Comment by symoore90** [comment]
Should I move the end date to Q3 or Q4? @travissluka

**Comment by travissluka** [comment]
Q3, but hopefully this can be wrapped up by the end of the month

**Comment by travissluka** [comment]
closing.

- Regional work will be covered by https://github.com/JCSDA-internal/aop24/issues/13
