### ISSUE TITLE
ALGO-72.1: Use generic OOPS masked interpolation with SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#876]
remove the bespoke interpolator used in SOCA

* [x] adopt the OOPS generic interpolator in the soca code
* [x] modify certain UFO operators to work with / ignore missing values due to land
* [x] check our diagnostics to make sure they work with the report missing value hofx
