### ISSUE TITLE
ALGO-72.2: Cleanup existing SOCA variable changes

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#877]
in preparation for VADER usage and/or the additional variable changes planned for this year (e.g. log transform, u/v geostrophy)

potential tasks
* [ ] identify list of variables and refine to have unique variable names throughout the variable transform process (e.g. based on balanced/unbalanced, rotated/unrotated, staggered/unstaggerd, etc)
* [x] hook in VADER
* [ ] change variable change classes to operate in a manner that works with VADER (i.e. get rid of separate `Model2GeoVaLs`, `Ana2Model`, and `Soca2Cice` and classes and work automatically based on input/output variables.

**Comment by shlyaeva** [comment]
@travissluka for the list of variables and identifying unique names it would be great to tie that in with the model variable naming convention; @svahl991 is organizing this effort.

**Comment by symoore90** [comment]
Does this epic need to be extended into Q3? @travissluka

**Comment by travissluka** [comment]
closing. any remaining work will be covered by https://github.com/JCSDA-internal/aop24/issues/10
