### ISSUE TITLE
TECHX-14.1: use UFS marine skylab forecasts/ SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#903]
## Description
Use the UFS marine (ng-godas) forecast in skylab with cycling 3dvar 

- [x] Prepare obs for feb/mar period in r2d2
- [x] Prepare the backgrounds for feb/mar period
- [x] have a pre-compiled marine UFS executable we can point to
- [x] get static files we need for the forecast model (atm forcing, other MOM6 needed files)
- [ ] make it all work in Skylab.
- [ ] celebrate

**Comment by kbhargava** [comment]
Quick status update on the tasks 
 

- [ ] **Prepare obs for feb/mar period in r2d2** : SSH done and ADT in progress
- [ ]  **Prepare the backgrounds for feb/mar period:** check with @travissluka
- [ ]  **have a pre-compiled marine UFS executable we can point to**: Compiled using intel on orion. The executable can be dound at `/work/noaa/marine/kritib/sandboxes/ufs-weather-model/build`
- [ ]  **get static files we need for the forecast model (atm forcing, other MOM6 needed files)** : Forcing files on orion at `/work/noaa/marine/marineda/soca-shared/DATA/forc/GFS` and static files at ``/work/noaa/marine/marineda/soca-shared/DATA/UFS_MOM6/INPUT/``
- [ ]   **make it all work in Skylab.**
- [ ]   **celebrate**

**Comment by kbhargava** [comment]
@travissluka Can we call our forecast setup with standalone good enough and close this?

**Comment by travissluka** [comment]
closing. Parts of this will be picked up by https://github.com/JCSDA-internal/aop24/issues/11
