### ISSUE TITLE
ALGO-72.3: Use SABER directly/correctly in SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#905]
## Description
Use SABER the way it's meant to be used.

* [x] finish explicit diffusion
* [x] delete/deprecate `SocaError` custom error covariance class
* [ ] delete/deprecate `BkgErr`
* [x] delete/deprecate `BkgErrFilt`
* [x] delete/deprecate `HorizFilt`
* [ ] move `BkgErrGodas` to a SABER outer block
* [x] delete/deprecate `VertConv`

**Comment by travissluka** [comment]
closing, parts of this will be picked up by https://github.com/JCSDA-internal/aop24/issues/11
