### ISSUE TITLE
TECHX-13.1: Prepare/verify SST sensitive IR/MW obs for golden month

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#907]
* [x] microwave (GMI/AMSR): check to see if we already have obs in R2D2 that have the channels needed for SST-sensitive DA w/ CRTM
* [x] infrared (AVHRR and/or VIIRS): check to see if we already have obs in R2D2 that have the channels needed for SST-sensitive DA w/ CRTM
* [x] If not already present: convert obs, put in R2D2 DB
* ~[ ] test with atmosphere (non-coupled) hofx in skylab~ (skipping, we'll jump straight to coupled hofx next quarter)

**Comment by symoore90** [comment]
Any update from Hamideh on this? @travissluka

**Comment by HamidehGMAO** [comment]
The GMI and amsr2 data for both 2021 and 2022 periods are already in r2d2 database and both instruments have channels around and less than 10GHz which are sensitive to SST

**Comment by travissluka** [comment]
note: MW obs are good, but we still need IR obs added to r2d2
