### ISSUE TITLE
OBSPROC-92.2: add non-PACE ocean color sensitive radiance observations to R2D2 database

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#908]
since the PACE synthetic observations are not available during our golden month of Aug 2021 _(someone check if I'm correct about that...)_ we need ocean color observations for another satellite added to R2D2 database for this time period for our skylab testing / demonstration.

- [x] Determine which satellite(s)/sensor(s) to use. (VIIRS / MODIS ?)
- [x] sort out the TOA/BOA issues
- [x] convert obs, put in DB

**Comment by HamidehGMAO** [comment]
I'm going to add aqua-MODIS L2 data from https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-2/Aqua-MODIS/2022/046/ to the dataset

**Comment by HamidehGMAO** [comment]
this data just has remote sensing reflectance we can drive water leaving radiances from it, so we do not have the TOA radiance issue like pace here.
