### ISSUE TITLE
Use VADER for insitu/potential temperature conversion in SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#923]
## Description
The insitu/potential temperature conversion is currently being performed in UFO (via `InsituTemperature`), but this requires a separate vertical interpolation that also does this conversion. If we add a recipe to VADER to do the conversion, we can then use the generic vertical interpolator that is in UFO. We can then depreciate, and eventually remove, the `InsituTemperature` observation operator. The code should be cleaner and more maintainable this way. 

We'll also want to sort out the model names, afterward, before this is used by other people (e.g. ROMS)

* [x] Add GSW support to VADER
* [x] Add the non-linear insitu/potential temperature recipe to VADER
* [ ] Add the linear insitu/potential temperature recipe to VADER
* [ ] Change the yamls in SOCA / Skylab to use the generic vertical interpolator and VADER recipe.
* [ ] Compare the two methods (conversion in VADER vs conversion in UFO) it _shouldn't_ make a big difference, but who knows

**Comment by travissluka** [comment]
@hga007 FYI, since you were interested in this. We hope to get this implemented this quarter.

**Comment by symoore90** [comment]
Does this epic need to be extended into Q3? @travissluka

**Comment by symoore90** [comment]
Extend to Q4? @travissluka

**Comment by travissluka** [comment]
> Extend to Q4? @travissluka

yes
