### ISSUE TITLE
Get marine obs for the Feb period

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#976]
## Description
Prepare the ocean obs for time period Feb 15-Mar 15 2022 and request to be put into R2D2.
This is an epic to track what needs to be done, individual issues / PRs should be opened at https://github.com/JCSDA-internal/r2d2-ingest

First:
- [ ] Check with EMC and/or what is on Orion to see if the following list is correct
- [ ] we are going to be using 6 hour windows, so check if we need to change how the obs are combined (right now they're all `P1D`, can we leave it that way?)

Observations needed:
- ADT
  - [x] Sentinel-3A
  - [x] Sentinel-3B
  - [x] Cryosat-2
  - [x] Jason-3
  - [x] SARAL
- ice concentration
  - [ ] SSMIS F17 retrieval
  - [ ] SSMIS F18 retrieval
- ice freeboard
  - [ ] ?
- SST retrievals
  - [x] AVHRR MetOp-B
  - [x] AVHRR MetOp-C
  - [x] VIIRS ??
- SSS retreivals
  - [ ] SMAP ?
  - [ ] SMOS ?
- insitu obs
  - [ ] FNMOC (or are the BUFR obs ready?)

**Comment by travissluka** [comment]
@kbhargava @guillaumevernieres @ShastriPaturi I just wanted to get everyone possibly interested tagged here.

@ShastriPaturi are observations available for Feb/Mar of 2023? We need to switch to this new time period because that's what the atmo people are doing here and we want to start running coupled DA in Skylab. If the obs are not available, perhaps @kbhargava could help you prepare some of them?

**Comment by ShastriPaturi** [comment]
> @kbhargava @guillaumevernieres @ShastriPaturi I just wanted to get everyone possibly interested tagged here.
> 
> @ShastriPaturi are observations available for Feb/Mar of 2023? We need to switch to this new time period because that's what the atmo people are doing here and we want to start running coupled DA in Skylab. If the obs are not available, perhaps @kbhargava could help you prepare some of them?

@travissluka the obs are available for Feb/March 2023 from the NCEP data tanks and they need to be dumped 6-hourly. The same is true for in situ BUFR. All these data need to be transferred from WCOSS2 to hera/orion.

I can start working on this and prepare the data. However, the 6-hourly dumps for in situ BUFR may take time since this is being handled by the ObsProc team.

**Comment by travissluka** [comment]
@ShastriPaturi thanks! If we could get the AVHRR SST retrievals processed by the end of the month, that would be helpful. The others can take their time. (Ideally, we would like all the obs this quarter, but realistically, the AVHRR ones are the most useful right now because we would also like to also start doing coupled DA comparisons with direct IR radiance assimilation with CRTM https://github.com/JCSDA-internal/AOP23/issues/124)

**Comment by ShastriPaturi** [comment]
@travisluka, you need the AVHRR SST superobbed to global 1/4 deg grid we are using or your 1/4 deg HAT10 domain?

**Comment by travissluka** [comment]
> @travisluka, you need the AVHRR SST superobbed to global 1/4 deg grid we are using or your 1/4 deg HAT10 domain?

The same as what you'll be using, the superobbed 1/4deg global

**Comment by travissluka** [comment]
I was wrong about the period, it's Feb-Mar 2022. I'm not sure what I was thinking. @ShastriPaturi does that change your answer on what obs are already processed?

**Comment by kbhargava** [comment]
Quick update. I have processed the AVHRR and VIIRS NPP nand N20 observations for R2D2 on orion. Refer https://github.com/JCSDA-internal/r2d2-ingest/issues/79
Thanks @ShastriPaturi for providing the observations.
